use_default_settings: true
server:
  port: 12783
  bind_address: "127.0.0.1"
  secret_key: "free-search-local-dev-key"
search:
  safe_search: 0
  formats:
    - html
    - json
engines:
  - name: wikipedia
    disabled: false
  - name: wikidata
    disabled: false
